apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30100
  selector:
    app: netflix-app
